_welcome:
    path:     /
    defaults: { _controller: DanWasHereBundle:Welcome:index }

_contact:
    path:     /contact
    defaults: { _controller: DanWasHereBundle:Contact:index }

_flash_workshop:
    path:     /flash_workshop
    defaults: { _controller: DanWasHereBundle:FlashWorkshop:index }

_portfolio:
    path:     /portfolio
    defaults: { _controller: DanWasHereBundle:Portfolio:index }

